#!/usr/bin/python3
import os
_str = os.environ.get("STR1")
print(_str, end="\n\n")
_str = os.environ.get("STR2")
print(_str)
_str = os.environ.get("STR3")
print(_str)
_str = os.environ.get("STR4")
print(_str)
_str = os.environ.get("STR5")
print(_str)
_str = os.environ.get("STR6")
print(_str)
_str = os.environ.get("STR7")
print(_str)
_str = os.environ.get("STR8")
print(_str)
_str = os.environ.get("STR9")
print(_str)
_str = os.environ.get("STR10")
print(_str)
_str = os.environ.get("STR11")
print(_str)
_str = os.environ.get("STR12")
print(_str)
_str = os.environ.get("STR13")
print(_str)
_str = os.environ.get("STR14")
print(_str)
_str = os.environ.get("STR15")
print(_str)
_str = os.environ.get("STR16")
print(_str)
_str = os.environ.get("STR17")
print(_str)
_str = os.environ.get("STR18")
print(_str)
_str = os.environ.get("STR19")
print(_str)
_str = os.environ.get("STR20")
print(_str)
